spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:flyway-sample;MODE=MYSQL
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  flyway:
    enabled: true